# -*- coding: utf-8 -*-
"""script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_aDk9SFBD4LY005h4nxJwzlXA2zyebY1
"""

from google.colab import drive
from PIL import Image
import os
from os import walk
import matplotlib.pyplot as plt

import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import torch.nn as nn
import torch.optim as optim

drive.mount('/content/drive')

train_a = "/content/drive/My Drive/CGAN_MONET/data/trainA.zip"
train_b = "/content/drive/My Drive/CGAN_MONET/data/trainB.zip"
path_a = "/content/photos"
path_b = "/content/monet"

!unzip -q "/content/drive/My Drive/CGAN_MONET/data/trainA.zip" -d "/content/photos"
!unzip -q "/content/drive/My Drive/CGAN_MONET/data/trainB.zip" -d "/content/monet"

monet = []
photos = []
for root, dir, files in walk('/content/monet'):
  for f in files:
    monet.append(os.path.join(path_b, f))

for root, dir, files in walk('/content/photos'):
  for f in files:
    photos.append(os.path.join(path_a, f))

fig, ax = plt.subplots(ncols = 2, figsize = (15, 5))
ax[0].imshow(Image.open(monet[10]))
ax[0].set_title("Claude Monet")
ax[0].axis('off')
ax[1].imshow(Image.open(photos[10]))
ax[1].set_title("Normal Image")
ax[1].axis('off')

class DatasetCGAN:
  def __init__(self, photo_paths, monet_paths, transform = None):
    self.photo_paths = photo_paths
    self.monet_paths = monet_paths
    self.transform = transform

    self.photo_len = len(photo_paths)
    self.monet_len = len(monet_paths)

    self.dataset_len = max(self.photo_len, self.monet_len)

  def __len__(self):
    return self.dataset_len

  def __getitem__(self, index):
    photo_path = self.photo_paths[index % self.photo_len]
    monet_path = self.monet_paths[index % self.monet_len]

    photo_img = Image.open(photo_path).convert('RGB')
    monet_img = Image.open(monet_path).convert('RGB')

    if self.transform:
      photo_img = self.transform(photo_img)
      monet_img = self.transform(monet_img)

    return photo_img, monet_img

transforms = T.Compose([
    T.Resize((256, 256)),
    T.RandomHorizontalFlip(p = 0.5),
    T.ToTensor(),
    T.Normalize(mean = [0.5, 0.5, 0.5], std = [0.5, 0.5, 0.5])
    ])

dataset = DatasetCGAN(photo_paths= photos, monet_paths= monet, transform= transforms)

dataloader = DataLoader(dataset = dataset, batch_size = 1, shuffle = True, num_workers = 2)

test_photo, test_monet = next(iter(dataloader))

print(test_photo.shape)
print(test_monet.shape)

class Encoder(nn.Module):
  def __init__(self, in_channels, out_channels,
               kernel_size, stride, padding, use_relu = True):
    super().__init__()
    self.conv = nn.Sequential(
        nn.ReflectionPad2d(padding) if padding > 0 else nn.Identity(),
        nn.Conv2d(in_channels, out_channels, kernel_size, stride,
                  padding = 0 if padding > 0 else padding, bias = True),
        nn.InstanceNorm2d(out_channels),
        nn.ReLU(inplace= True) if use_relu else nn.Identity()
    )

  def forward(self, x):
    return self.conv(x)

class Residual(nn.Module):
  def __init__(self, channels):
    super().__init__()
    self.block = nn.Sequential(
        nn.ReflectionPad2d(1),
        nn.Conv2d(channels, channels, kernel_size= 3, padding = 0),
        nn.InstanceNorm2d(channels),
        nn.ReLU(inplace = True),

        nn.ReflectionPad2d(1),
        nn.Conv2d(channels, channels, kernel_size = 3, padding = 0),
        nn.InstanceNorm2d(channels)
    )

  def forward(self, x):
    return x + self.block(x)

class Decoder(nn.Module):
  def __init__(self, in_channels, out_channels, kernel_size, stride,
               padding, output_padding):
    super().__init__()
    self.upsample = nn.Sequential(
        nn.ConvTranspose2d(in_channels, out_channels, kernel_size, stride, padding,
                           output_padding, bias = True),
        nn.InstanceNorm2d(out_channels),
        nn.ReLU(inplace = True)
    )

  def forward(self, x):
    return self.upsample(x)

class Generator(nn.Module):
  def __init__(self, img_channels = 3, num_features = 64, num_residual = 9):
    super().__init__()

    self.initial = Encoder(img_channels, num_features, kernel_size= 7, stride = 1,
                           padding = 3)
    self.downsample_1 = Encoder(num_features, num_features * 2, kernel_size = 3,
                                stride = 2, padding = 1)
    self.downsample_2 = Encoder(num_features * 2, num_features * 4, kernel_size = 3,
                                stride = 2, padding = 1)

    self.res_block = nn.Sequential(
        *[Residual(num_features * 4) for _ in range(num_residual)]
    )

    self.upsample_1 = Decoder(num_features * 4, num_features * 2, kernel_size= 3,
                              stride = 2, padding = 1, output_padding= 1)
    self.upsample_2 = Decoder(num_features * 2, num_features, kernel_size= 3, stride = 2,
                              padding = 1, output_padding= 1)

    self.last = nn.Sequential(
        nn.ReflectionPad2d(3),
        nn.Conv2d(num_features, img_channels, kernel_size= 7, padding = 0),
        nn.Tanh()
    )

  def forward(self, x):
    x = self.initial(x)
    x = self.downsample_1(x)
    x = self.downsample_2(x)
    x = self.res_block(x)
    x = self.upsample_1(x)
    x = self.upsample_2(x)
    return self.last(x)

class Discriminator(nn.Module):
  def __init__(self, img_channels = 3, features = [64, 128, 256, 512]):

    super().__init__()

    self.initial = nn.Sequential(
        nn.Conv2d(img_channels, features[0], kernel_size = 4, stride = 2, padding = 1),
        nn.LeakyReLU(0.2, inplace = True)
    )

    layers = []

    in_channels = features[0]
    for feature in features[1:]:
      stride = 1 if feature == features[-1] else 2
      layers.append(
          nn.Sequential(
              nn.Conv2d(in_channels, feature, kernel_size=4, stride = stride, padding = 1,
                        padding_mode= 'reflect'),
              nn.InstanceNorm2d(feature),
              nn.LeakyReLU(0.2,  inplace = True)
          )
      )
      in_channels = feature

    self.layers = nn.Sequential(*layers)

    self.patch_out = nn.Conv2d(in_channels, 1, kernel_size = 4, stride = 1,
                               padding = 1, padding_mode = 'reflect')

  def forward(self, x):
    x = self.initial(x)
    x = self.layers(x)
    return self.patch_out(x)

x = torch.rand(1, 3, 256, 256)

gen = Generator()
disc = Discriminator()

print(f"Input shape:        {x.shape}")
print(f"Generator output:   {gen(x).shape}")
print(f"Discriminator grid: {disc(x).shape}")

device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)

gen_A2B = Generator().to(device) # normal to Monet
gen_B2A = Generator().to(device) # Monet to normal

disc_A = Discriminator().to(device) # Is this a real photo ?
disc_B = Discriminator().to(device) # Is this a real Monet ?

opt_gen = optim.Adam(
    list(gen_A2B.parameters()) + list(gen_B2A.parameters()),
    lr = 2e-4,
    betas = (0.5, 0.999)
)
opt_dis = optim.Adam(
    list(disc_A.parameters()) + list(disc_B.parameters()),
    lr = 2e-4,
    betas = (0.5, 0.999)
)

mse_loss = nn.MSELoss() # Did we fool the Judge
l1_loss = nn.L1Loss() # translation error

from tqdm import tqdm

def train_fn(disc_A, disc_B, gen_A2B, gen_B2A, dataloader, opt_dis,
             opt_gen, mse_loss, l1_loss, device):
  disc_A.train()
  disc_B.train()
  gen_A2B.train()
  gen_B2A.train()

  loop = tqdm(dataloader, leave = True)

  for idx, (real_photo, real_monet) in enumerate(loop):

    #### Train Generators
    real_photo = real_photo.to(device)
    real_monet = real_monet.to(device)

    opt_gen.zero_grad()

    # Loss of fooling detective
    fake_monet = gen_A2B(real_photo)
    disc_B_fake_pred = disc_B(fake_monet)
    loss_G_A2B_adv = mse_loss(disc_B_fake_pred, torch.ones_like(disc_B_fake_pred))
    fake_photo = gen_B2A(real_monet)
    disc_A_fake_pred = disc_A(fake_photo)
    loss_G_B2A_adv = mse_loss(disc_A_fake_pred, torch.ones_like(disc_A_fake_pred))

    # Loss in translation (like the movie)
    rec_photo = gen_B2A(fake_monet)
    loss_cycle_photo = l1_loss(real_photo, rec_photo) * 10.0
    rec_monet = gen_A2B(fake_photo)
    loss_cycle_monet = l1_loss(real_monet, rec_monet) * 10.0

    # loss in identity

    id_monet = gen_A2B(real_monet)
    loss_id_monet = l1_loss(real_monet, id_monet) * 5.0
    id_photo = gen_B2A(real_photo)
    loss_id_photo = l1_loss(real_photo, id_photo) * 5.0

    total_loss_G = (
            loss_G_A2B_adv + loss_G_B2A_adv +
            loss_cycle_photo + loss_cycle_monet +
            loss_id_photo + loss_id_monet
        )

    total_loss_G.backward()
    opt_gen.step()


############# Train detectives
    opt_dis.zero_grad()

#### Train monet detective
    dis_B_real_pred = disc_B(real_monet)
    loss_disc_B_real = mse_loss(dis_B_real_pred, torch.ones_like(dis_B_real_pred))
    disc_B_fake_pred = disc_B(fake_monet.detach())
    loss_disc_B_fake = mse_loss(disc_B_fake_pred, torch.zeros_like(disc_B_fake_pred))
    loss_disc_B = (loss_disc_B_real + loss_disc_B_fake) * 0.5

    # real photo detective
    disc_A_real_pred = disc_A(real_photo)
    loss_disc_A_real = mse_loss(disc_A_real_pred, torch.ones_like(disc_A_real_pred))
    disc_A_fake_pred = disc_A(fake_photo.detach())
    loss_disc_A_fake = mse_loss(disc_A_fake_pred, torch.zeros_like(disc_A_fake_pred))
    loss_disc_A = (loss_disc_A_real + loss_disc_A_fake) * 0.5


    total_loss_D = loss_disc_B + loss_disc_A

    total_loss_D.backward()
    opt_dis.step()

    if idx % 10 == 0:
      loop.set_postfix(Loss_G = total_loss_G.item(), Loss_D = total_loss_D.item())

def save_and_show_progress(gen_A2B, gen_B2A, test_photo, device, epoch):
    # Set to evaluation mode
    gen_A2B.eval()
    gen_B2A.eval()

    with torch.no_grad():

        real_photo = test_photo.to(device)


        fake_monet = gen_A2B(real_photo)

        rec_photo = gen_B2A(fake_monet)

        img_real = (real_photo.squeeze(0) * 0.5 + 0.5).permute(1, 2, 0).cpu().numpy()
        img_fake = (fake_monet.squeeze(0) * 0.5 + 0.5).permute(1, 2, 0).cpu().numpy()
        img_rec  = (rec_photo.squeeze(0) * 0.5 + 0.5).permute(1, 2, 0).cpu().numpy()

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    axes[0].imshow(img_real)
    axes[0].set_title(f"Original Photo")
    axes[0].axis("off")

    axes[1].imshow(img_fake)
    axes[1].set_title(f"Generated Monet (Epoch {epoch})")
    axes[1].axis("off")

    axes[2].imshow(img_rec)
    axes[2].set_title(f"Reconstructed Photo")
    axes[2].axis("off")

    plt.tight_layout()
    plt.show()
    gen_A2B.train()
    gen_B2A.train()

fixed_photo, _ = next(iter(dataloader))

NUM_EPOCHS = 5

for epoch in range(NUM_EPOCHS):
    print(f"\n Epoch {epoch+1}/{NUM_EPOCHS}")

    train_fn(
        disc_A=disc_A,
        disc_B=disc_B,
        gen_A2B=gen_A2B,
        gen_B2A=gen_B2A,
        dataloader=dataloader,
        opt_dis=opt_dis,
        opt_gen=opt_gen,
        mse_loss=mse_loss,
        l1_loss=l1_loss,
        device=device
    )

    save_and_show_progress(gen_A2B, gen_B2A, fixed_photo, device, epoch = epoch + 1)

checkpoint = {
        "epoch": epoch,
        "gen_A2B_state_dict": gen_A2B.state_dict(),
        "gen_B2A_state_dict": gen_B2A.state_dict(),
        "disc_A_state_dict": disc_A.state_dict(),
        "disc_B_state_dict": disc_B.state_dict(),
        "opt_gen_state_dict": opt_gen.state_dict(),
        "opt_disc_state_dict": opt_dis.state_dict(),
    }

torch.save(checkpoint, "/content/drive/MyDrive/CGAN_MONET/cyclegan_checkpoint.pth")

